### PR TITLE
Bug fix for range command

### LINKED ISSUE #224: Bugs - Range command
# Issue

The range command works but I noticed a few issues while testing
1. The example text is wrong, it should be something along the lines of
`range editperson a/Address For Persons 1 to 3 from/1 to/3`
Screenshot 2022-03-24 at 7 34 02 PM

2. If a invalid param is passed through (i.e, phone number of 1 digit) , an exception happens

usually, if you do an `editperson 2 p/1` it will show smth like this
Screenshot 2022-03-24 at 7 38 42 PM

however, if a similar operation is performed using range, it somehow defaults to the normal invalid command error. i can see how this may be a more complicated fix 

https://user-images.githubusercontent.com/13099969/159909041-4f27bdf2-1a02-4724-89b9-3947c2235681.mov

3. number parse exception if parse in alphabets into the `from/` and `to/`. should be a pretty simple fix, but this one most impt to fix as it causes exception 
Screenshot 2022-03-24 at 7 44 11 PM

### PR DESCRIPTION
**Pull request by HanJiyao**
This PR fixed the 3 issue highlighted, as the sample, parse error message and index validation.

Closes #224

### CODE REVIEW

File: src/main/java/seedu/contax/logic/commands/RangeCommand.java [hunk 1]
```diff
@@ -34,7 +33,9 @@
             + PREFIX_RANGE_TO + "TO *\n"
             + "Example: `" + COMMAND_WORD + " edit "
             + PREFIX_PHONE + "12345678 "
-            + PREFIX_ADDRESS + "New Address `";
+            + PREFIX_ADDRESS + "New Address "
+            + PREFIX_RANGE_FROM + "1 "
+            + PREFIX_RANGE_TO + "3 `\n";
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/logic/commands/RangeCommand.java:38]: There is no need for the trailing breakline.

File: src/main/java/seedu/contax/logic/parser/RangeCommandParser.java [hunk 2]
```diff
@@ -31,13 +30,20 @@ public RangeCommand parse(String args) throws ParseException {
...
 
         if (argMultimap.getValue(PREFIX_RANGE_FROM).isPresent() && argMultimap.getValue(PREFIX_RANGE_TO).isPresent()) {
-            fromIndex = Index.fromOneBased(Integer.parseInt(argMultimap.getValue(PREFIX_RANGE_FROM).get()));
-            toIndex = Index.fromOneBased(Integer.parseInt(argMultimap.getValue(PREFIX_RANGE_TO).get()));
+            try {
+                fromIndex = ParserUtil.parseIndex(argMultimap.getValue(PREFIX_RANGE_FROM).get());
+                toIndex = ParserUtil.parseIndex(argMultimap.getValue(PREFIX_RANGE_TO).get());
+            } catch (ParseException pe) {
+                throw new ParseException(String.format(MESSAGE_INVALID_RANGE_INDEX,
+                        RangeCommand.MESSAGE_USAGE), pe);
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:38]: I think you should explicitly say that the index is invalid, instead of just displaying the syntax.

File: src/main/java/seedu/contax/logic/parser/RangeCommandParser.java [hunk 3]
```diff
@@ -31,13 +30,20 @@ public RangeCommand parse(String args) throws ParseException {
...
+            }
             if (fromIndex.getZeroBased() > toIndex.getZeroBased()) {
-                throw new ParseException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
+                throw new ParseException(String.format(MESSAGE_INVALID_RANGE_INDEX,
+                        RangeCommand.MESSAGE_USAGE));
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:42]: I think you should explicitly state the error (from > to), rather than a generic message.

File: src/main/java/seedu/contax/logic/parser/RangeCommandParser.java [hunk 4]
```diff
@@ -31,13 +30,20 @@ public RangeCommand parse(String args) throws ParseException {
...
             }
         } else {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, RangeCommand.MESSAGE_USAGE));
+            throw new ParseException(String.format(MESSAGE_INVALID_RANGE_INDEX,
+                    RangeCommand.MESSAGE_USAGE));
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:46]: You should handle this as a guard clause instead of a else clause, that is, to have a `(argMultimap.getValue(PREFIX_RANGE_FROM).isEmpty() || argMultimap.getValue(PREFIX_RANGE_TO).isEmpty())` above

File: src/main/java/seedu/contax/logic/commands/RangeCommand.java (hunk 1 above)
Comment (HanJiyao) [reply src/main/java/seedu/contax/logic/commands/RangeCommand.java:38]: thx removed

File: src/main/java/seedu/contax/logic/parser/RangeCommandParser.java (hunk 2 above)
Comment (HanJiyao) [reply src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:38]: thx changed

File: src/main/java/seedu/contax/logic/parser/RangeCommandParser.java (hunk 3 above)
Comment (HanJiyao) [reply src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:42]: thx changed

File: src/main/java/seedu/contax/logic/parser/RangeCommandParser.java (hunk 4 above)
Comment (HanJiyao) [reply src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:46]: thx changed

File: src/main/java/seedu/contax/logic/parser/RangeCommandParser.java [hunk 5]
```diff
@@ -27,18 +29,26 @@ public RangeCommand parse(String args) throws ParseException {
...
-        Index toIndex;
+        Index fromIndex = Index.fromZeroBased(0);
+        Index toIndex = Index.fromZeroBased(0);
+
+        if (argMultimap.getValue(PREFIX_RANGE_FROM).isEmpty() || argMultimap.getValue(PREFIX_RANGE_TO).isEmpty()) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                    RangeCommand.MESSAGE_USAGE));
+        }
 
         if (argMultimap.getValue(PREFIX_RANGE_FROM).isPresent() && argMultimap.getValue(PREFIX_RANGE_TO).isPresent()) {
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:40]: Is this a redundant check now that you have the guard clause from above?

File: src/main/java/seedu/contax/logic/parser/RangeCommandParser.java [hunk 6]
```diff
@@ -27,18 +29,26 @@ public RangeCommand parse(String args) throws ParseException {
 
         String commandInput = argMultimap.getPreamble();
 
-        Index fromIndex;
-        Index toIndex;
+        Index fromIndex = Index.fromZeroBased(0);
+        Index toIndex = Index.fromZeroBased(0);
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:33]: You should move this to after this guard clause.

Comment (HanJiyao) [reply src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:33]: this is init only shd be same, but yes can move

File: src/main/java/seedu/contax/logic/commands/RangeCommand.java [hunk 7]
```diff
@@ -34,7 +33,9 @@
             + PREFIX_RANGE_TO + "TO *\n"
             + "Example: `" + COMMAND_WORD + " edit "
```
Comment (dandaandaaaaaan) [inline src/main/java/seedu/contax/logic/commands/RangeCommand.java:34]:
```suggestion
            + "Example: `" + COMMAND_WORD + " editperson "
```
remember to change this too

Comment (HanJiyao) [reply src/main/java/seedu/contax/logic/commands/RangeCommand.java:34]: thx for the point

File: src/main/java/seedu/contax/logic/parser/RangeCommandParser.java (hunk 5 above)
Comment (HanJiyao) [reply src/main/java/seedu/contax/logic/parser/RangeCommandParser.java:40]: the above guard is it requireNonNull(args)? it only conatin entire args

**Review by dandaandaaaaaan — APPROVED** [review]
lgtm thanks

**Review by Wei-Xinn — APPROVED** [review]
lgtm
