### PR TITLE
Fix - Person-Tag Integrity Enforcement

### LINKED ISSUE #160: Refactor Person-Tag Integrity Enforcement
## Current Issue
- Currently, the synchronization between the persons and tags in the `AddressBook` is handled at the Logic component. This requires all functions modifying either persons or tags to ensure maintenance of both lists, which can cause bugs and result in an inconsistent Model instance if either is done incorrectly.

## Proposed Change
- The integrity enforcement should be shifted to the Model component, which provides a tighter integrity enforcement and will never allow the Model to be in an inconsistent state.
- This would entail the following changes in `Model`
  - `addPerson()` adding new tags to the tag list
  - `setPerson()` updates the tag list based on removals / additions of tags
  - `deletePerson()` removing tags from the tag list
  - `deleteTag()` removes the deleted tag from all Persons
  - `setTag()` updates the tags in all Persons with the old Tag

### PR DESCRIPTION
**Pull request by KwanHW**
# Changes
This PR provides tighter integrity enforcement in the Person-Tag relationship by moving the synchronisation logic from the `Logic` component to the `Model` component. 

# Related Issues
- Fixes #160

### CODE REVIEW

File: src/main/java/seedu/contax/model/AddressBook.java [hunk 1]
```diff
@@ -115,14 +117,74 @@ public boolean hasTag(Tag tag) {
...
+     */
+    public void setTag(Tag target, Tag editedTag) {
+        tags.setTag(target, editedTag);
+        setPersonsWithTag(target, editedTag);
+    }
+
+    /**
+     * Disassociates the specified tag from all persons in the address book.
+     */
+    private void removePersonsWithTag(Tag tagToDelete) {
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/model/AddressBook.java:150]: Consider renaming this because it sounds like the person is being removed.
```suggestion
    private void removeTagFromPersons(Tag tagToDelete) {
```

File: src/main/java/seedu/contax/model/AddressBook.java [hunk 2]
```diff
@@ -115,14 +117,74 @@ public boolean hasTag(Tag tag) {
...
+        requireNonNull(tagToDelete);
+        List<Person> persons = getPersonList().filtered(person -> person.getTags().contains(tagToDelete));
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/model/AddressBook.java:152]: I think you should be consistent with what you coded below in `setPersonsWithTag` (I think the implementation below is neater).
```suggestion
        List<Person> persons = getPersonList().filtered(person -> person.hasTag(tagToDelete));
```

File: src/main/java/seedu/contax/model/ModelManager.java [hunk 3]
```diff
@@ -167,17 +167,12 @@ public void addTag(Tag tag) {
...
 
-    private void removeTagFromPersons(Tag tagToDelete) {
-        requireNonNull(tagToDelete);
-        List<Person> persons = addressBook.getPersonList().filtered(person -> person.getTags().contains(tagToDelete));
-        for (int i = 0; i < persons.size(); i++) {
-            Person oldPerson = persons.get(i);
-            setPerson(oldPerson, oldPerson.withoutTag(tagToDelete));
-        }
+    @Override
+    public void setTag(Tag target, Tag editedTag) {
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/model/ModelManager.java:174]: Consider adding `requireNonNull` here.

File: src/main/java/seedu/contax/model/person/Person.java [hunk 4]
```diff
@@ -82,6 +82,10 @@ public Person withoutTag(Tag tag) {
         return new Person(name, phone, email, address, updatedTag);
     }
 
+    public boolean hasTag(Tag tag) {
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/model/person/Person.java:85]: Missing Javadocs, though, I think this is fairly self-explanatory.

File: src/main/java/seedu/contax/model/tag/UniqueTagList.java [hunk 5]
```diff
@@ -69,6 +69,19 @@ public void setTags(List<Tag> tags) {
         internalList.setAll(tags);
     }
 
+    public void setTag(Tag target, Tag editedTag) {
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/model/tag/UniqueTagList.java:72]: Missing javadocs.

File: src/main/java/seedu/contax/model/tag/UniqueTagList.java [hunk 6]
```diff
@@ -69,6 +69,19 @@ public void setTags(List<Tag> tags) {
...
+        requireNonNull(target);
+        requireNonNull(editedTag);
+
+        // Checks if edited Tag exists
+        if (contains(editedTag)) {
+            throw new DuplicateTagException();
+        }
```
Comment (sharpstorm) [inline src/main/java/seedu/contax/model/tag/UniqueTagList.java:79]: This will fail if `target == editedTag`. You need to ignore the `target` tag.

**Review by sharpstorm — CHANGES_REQUESTED** [review]
I noticed only small issues, but I think they should be fixed.

File: src/main/java/seedu/contax/model/tag/UniqueTagList.java (hunk 6 above)
Comment (KwanHW) [reply src/main/java/seedu/contax/model/tag/UniqueTagList.java:87]: Fixed in 7ff3cf68

File: src/main/java/seedu/contax/model/tag/UniqueTagList.java (hunk 5 above)
Comment (KwanHW) [reply src/main/java/seedu/contax/model/tag/UniqueTagList.java:75]: Fixed in 7ff3cf68

File: src/main/java/seedu/contax/model/person/Person.java (hunk 4 above)
Comment (KwanHW) [reply src/main/java/seedu/contax/model/person/Person.java:88]: Fixed in 7ff3cf68

File: src/main/java/seedu/contax/model/ModelManager.java (hunk 3 above)
Comment (KwanHW) [reply src/main/java/seedu/contax/model/ModelManager.java:174]: Fixed in 7ff3cf68

File: src/main/java/seedu/contax/model/AddressBook.java (hunk 2 above)
Comment (KwanHW) [reply src/main/java/seedu/contax/model/AddressBook.java]: Fixed in 7ff3cf68

File: src/main/java/seedu/contax/model/AddressBook.java (hunk 1 above)
Comment (KwanHW) [reply src/main/java/seedu/contax/model/AddressBook.java]: Fixed in 7ff3cf68

**Review by sharpstorm — APPROVED** [review]
LGTM.

**Review by dandaandaaaaaan — APPROVED** [review]
lgtm! will pr one after this to remove a small set of code from my import
